project:
  type: website
  output-dir: docs

website:
  title: "DAT255 Course Project"
  navbar:
    right:
      - about.qmd
      - icon: github
        text: Nora Github
        href: https://github.com/NoraKri
      - icon: github
        text: Torbjørn Github
        href: https://github.com/torvat
format:
  html:
    theme: cosmo
    css: styles.css

